apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base/app

images:
- name: placeholder
  newName: placeholder
  newTag: latest # This tag will be updated by the CI pipeline
